"""A content brief for the handle: the post, plus the prompts to make its media.

This is social-first. It does not write a blog post - `/blog` does that. It plans
one piece of content for Instagram, TikTok and Shorts, and hands back ready-to-paste
prompts so the images or clips can be generated by hand in the Gemini app.

The model supplies only the IDEA for each visual. The house style is appended by
code, so every asset matches the last one and no tokens are spent restating it.

    uv run python -m src.social_studio.brief --topic "why your API is slow"
    uv run python -m src.social_studio.brief --topic "..." --format video
"""

import json
import os
import re
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage

from src.social_studio.slides import _extract_json, _invoke, _slugify

BRIEF_DIR = Path(__file__).resolve().parents[2] / "data" / "social" / "briefs"

# Veo generates fixed-length clips, so a video is built from several of them
# rather than one long take. Confirm the current limit in the Gemini app.
VEO_CLIP_SECONDS = 8
VIDEO_SCENES = (4, 6)
CAROUSEL_SLIDES = (6, 8)

# Single source of truth for the look. Mirrored in data/social/PROMPTS.md.
STYLE_BLOCK = (
    "Deep warm charcoal background (#121110) with subtle paper grain. Thin muted "
    "teal (#6fd3bf) linework as the primary element, sparse off-white (#f2efe9) "
    "accents. Minimal and restrained, generous negative space, high-end print "
    "magazine aesthetic. Convey the idea through geometry alone. Absolutely no "
    "text, no letters, no numbers, no UI elements, no code, no logos."
)

MOTION_BLOCK = (
    "Very slow, restrained motion. Static camera, no shake, no zoom, no cuts. "
    "It is a background behind on-screen text, so it must not compete for "
    "attention. Seamless loop. No people, no text, no logos."
)

SYSTEM = """You plan short-form content for a software engineer's social account.

This is NOT a blog post. It is one piece of content for Instagram, TikTok and
YouTube Shorts. What overperforms in this niche: a numbered or comparative frame,
exactly one idea per scene, concrete specifics, and no filler.

For each scene give:
- heading: at most 7 words, and it MUST be a claim or a finding, never a category
  label. "Not all 429s are equal", not "Rate Limit Types".
- body: 1-2 short sentences, under 200 characters.

NEVER INVENT A STATISTIC. This is the most important rule here. Do not write a
percentage, a multiple, a count or a benchmark unless it appears verbatim in the
supplied evidence. A specific-sounding number you made up ("40% of failures",
"3x faster") destroys the author's credibility the moment a reader checks it,
and it cannot be defended in the replies. With no evidence supplied, write from
mechanism and experience instead - explain WHY something happens, not how often.
A concrete explanation beats a fabricated measurement.
- visual: ONE short sentence describing the idea as pure geometry or motion -
  lines, paths, shapes, density, direction. No objects, no people, no text, no
  screens. Example: "parallel lines that fray and break, one surviving to the right".

Return STRICT JSON only, no prose:
{"title": "...", "kicker": "...", "hook": "...", "subtitle": "...",
 "scenes": [{"heading": "...", "body": "...", "visual": "..."}],
 "caption": "...", "hashtags": ["#..."]}

hook: the opening line. A specific claim or comparison, never a vague question.
kicker: 1-3 words naming the series, in caps.
caption: strong first line, then 2-3 short lines.
hashtags: 4-6, specific, no generic spam."""


def _clean(brief: dict, topic: str, fmt: str) -> dict:
    scenes = []
    for raw in brief.get("scenes") or []:
        heading = str(raw.get("heading", "")).strip()
        body = str(raw.get("body", "")).strip()
        if not heading and not body:
            continue
        visual = str(raw.get("visual", "")).strip()
        scenes.append({"heading": heading, "body": body, "visual": visual})

    limit = VIDEO_SCENES[1] if fmt == "video" else CAROUSEL_SLIDES[1]
    brief["scenes"] = scenes[:limit]
    brief["format"] = fmt
    brief["title"] = str(brief.get("title") or topic).strip()
    brief["hook"] = str(brief.get("hook") or brief["title"]).strip()
    brief["kicker"] = str(brief.get("kicker") or "").strip().upper()
    brief["subtitle"] = str(brief.get("subtitle") or "").strip()
    brief["caption"] = str(brief.get("caption") or "").strip()
    brief["hashtags"] = [
        h if str(h).startswith("#") else f"#{h}"
        for h in (brief.get("hashtags") or [])
        if str(h).strip()
    ][:6]
    brief["slug"] = _slugify(brief["title"])
    brief["handle"] = os.environ.get("SOCIAL_HANDLE", "").strip()
    return brief


def image_prompt(visual: str, aspect: str = "9:16") -> str:
    """Compose a paste-ready image prompt: the scene's idea plus the house style."""
    idea = visual.strip().rstrip(".") or "abstract geometric composition"
    return f"{idea[0].upper()}{idea[1:]}. {STYLE_BLOCK} Aspect ratio {aspect}."


def video_prompt(visual: str, aspect: str = "9:16") -> str:
    """Compose a Veo prompt for one fixed-length clip."""
    idea = visual.strip().rstrip(".") or "abstract geometric motion"
    return (
        f"{idea[0].upper()}{idea[1:]}, animated slowly over "
        f"{VEO_CLIP_SECONDS} seconds. {STYLE_BLOCK} {MOTION_BLOCK} "
        f"Vertical {aspect}."
    )


def attach_prompts(brief: dict) -> dict:
    """Add a media prompt to every scene, matched to the chosen format."""
    is_video = brief.get("format") == "video"
    for index, scene in enumerate(brief.get("scenes") or [], start=1):
        scene["index"] = index
        if is_video:
            scene["video_prompt"] = video_prompt(scene.get("visual", ""))
            scene["seconds"] = VEO_CLIP_SECONDS
        else:
            scene["image_prompt"] = image_prompt(scene.get("visual", ""))
    if is_video:
        brief["total_seconds"] = len(brief.get("scenes") or []) * VEO_CLIP_SECONDS
    return brief


def create_brief(topic: str, fmt: str = "carousel", evidence: str = "") -> dict:
    """Plan one piece of content and the prompts needed to make its media.

    `evidence` is first-hand material - your own metrics, logs or code. Supply it
    whenever the piece makes numerical claims: without it the model has nothing
    real to cite and will reach for invented statistics.
    """
    if fmt not in {"carousel", "video"}:
        raise ValueError(f"format must be 'carousel' or 'video', got {fmt!r}")

    low, high = VIDEO_SCENES if fmt == "video" else CAROUSEL_SLIDES
    instruction = (
        f"Topic: {topic}\n\nProduce {low} to {high} scenes for a "
        f"{'vertical video' if fmt == 'video' else 'swipeable carousel'}."
    )
    if evidence.strip():
        instruction += (
            "\n\nEVIDENCE - the only numbers you may use. Quote them exactly:\n"
            f"{evidence.strip()}"
        )
    else:
        instruction += (
            "\n\nNo evidence supplied, so use NO statistics at all. Explain the "
            "mechanism instead."
        )
    response = _invoke([SystemMessage(content=SYSTEM), HumanMessage(content=instruction)])
    brief = _clean(_extract_json(str(response.content)), topic, fmt)
    return attach_prompts(brief)


def save(brief: dict) -> Path:
    BRIEF_DIR.mkdir(parents=True, exist_ok=True)
    path = BRIEF_DIR / f"{brief['slug']}.json"
    path.write_text(json.dumps(brief, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def as_deck(brief: dict) -> dict:
    """Reshape a brief into the deck the slide renderer expects."""
    return {
        "slug": brief["slug"],
        "title": brief["title"],
        "kicker": brief.get("kicker", ""),
        "hook": brief.get("hook", ""),
        "subtitle": brief.get("subtitle", ""),
        "handle": brief.get("handle", ""),
        "outro": brief.get("outro") or "Save this for later.",
        "slides": [
            {"heading": s.get("heading", ""), "body": s.get("body", "")}
            for s in brief.get("scenes") or []
        ],
        "caption": brief.get("caption", ""),
        "hashtags": brief.get("hashtags") or [],
    }


def format_for_chat(brief: dict) -> str:
    """A copy-pasteable brief for Discord."""
    lines = [f"**{brief['title']}**", f"> {brief['hook']}", ""]
    is_video = brief["format"] == "video"
    if is_video:
        lines.append(
            f"**{len(brief['scenes'])} clips x {VEO_CLIP_SECONDS}s = "
            f"~{brief.get('total_seconds')}s total**\n"
        )
    for scene in brief["scenes"]:
        lines.append(f"**{scene['index']}. {scene['heading']}**")
        lines.append(scene["body"])
        key = "video_prompt" if is_video else "image_prompt"
        lines.append(f"```\n{scene[key]}\n```")
    ext = "mp4" if is_video else "png"
    lines.append(
        f"Generate each one, then send it back with "
        f"`/scene {brief['slug']} <number>` and the .{ext} attached."
    )
    return "\n".join(lines)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Plan a piece of social content")
    parser.add_argument("--topic", required=True)
    parser.add_argument("--format", default="carousel", choices=["carousel", "video"])
    args = parser.parse_args()

    brief = create_brief(args.topic, args.format)
    print(f"Brief saved -> {save(brief)}\n")
    print(re.sub(r"\*\*|```", "", format_for_chat(brief)))


if __name__ == "__main__":
    main()
