"""Collect the media generated by hand for a brief's scenes.

Files arrive one at a time from Discord, so this tracks which scene numbers have
landed and which are still outstanding.

    data/social/scenes/<slug>/01.png    carousel background
    data/social/scenes/<slug>/01.mp4    video clip
"""

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCENE_ROOT = PROJECT_ROOT / "data" / "social" / "scenes"
BRIEF_DIR = PROJECT_ROOT / "data" / "social" / "briefs"

IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".webp")
VIDEO_SUFFIXES = (".mp4",)


class SceneError(RuntimeError):
    pass


def load_brief(slug: str) -> dict:
    path = BRIEF_DIR / f"{slug}.json"
    if not path.exists():
        raise SceneError(f"no brief called {slug!r}. Run /content first.")
    return json.loads(path.read_text(encoding="utf-8"))


def scene_dir(slug: str) -> Path:
    directory = SCENE_ROOT / slug
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def target_path(slug: str, index: int, filename: str) -> Path:
    """Where scene N's file belongs, keeping the uploaded extension."""
    suffix = Path(filename).suffix.lower()
    if suffix not in IMAGE_SUFFIXES + VIDEO_SUFFIXES:
        raise SceneError(f"unsupported file type {suffix!r}")
    return scene_dir(slug) / f"{index:02d}{suffix}"


def collected(slug: str) -> dict[int, Path]:
    """Scene number -> file, for whatever has been uploaded so far."""
    directory = SCENE_ROOT / slug
    if not directory.is_dir():
        return {}
    found: dict[int, Path] = {}
    for path in sorted(directory.iterdir()):
        if path.suffix.lower() not in IMAGE_SUFFIXES + VIDEO_SUFFIXES:
            continue
        try:
            found[int(path.stem)] = path
        except ValueError:
            continue  # not a scene file
    return found


def status(brief: dict) -> dict:
    """What has arrived, what is missing, and whether assembly can run."""
    total = len(brief.get("scenes") or [])
    have = collected(brief["slug"])
    missing = [n for n in range(1, total + 1) if n not in have]
    return {
        "total": total,
        "have": sorted(have),
        "missing": missing,
        "ready": total > 0 and not missing,
        "files": have,
    }


def ordered_files(brief: dict) -> list[Path]:
    """Scene files in scene order. Raises if any are missing."""
    state = status(brief)
    if not state["ready"]:
        raise SceneError(
            f"missing scene(s) {', '.join(str(n) for n in state['missing'])} "
            f"of {state['total']}"
        )
    return [state["files"][n] for n in range(1, state["total"] + 1)]
