[project]
name = "multi-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddgs",
    "discord-py>=2.7.1",
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib",
    "langchain",
    "langchain-openai",
    "langgraph",
    "markdown>=3.10.3",
    "mcp",
    "openai",
    "pdfplumber",
    "python-dotenv",
    "yfinance>=1.5.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
